services:
  devcontainer:
    command: sh -c 'while sleep 1; do :; done'
    image: public.ecr.aws/acilearning/haskell:9.2.5-7bd251ac55c29968002b10e3d012562e86d3f218
    init: true
    volumes:
      - ..:/workspaces/witch
      - cabal:/home/haskell/.cabal
      - cabal-store:/cabal-store
    working_dir: /workspaces/witch
volumes:
  cabal: null
  cabal-store:
    external: true
