name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: ubuntu, ghc: 9.2.1 }
          - { os: ubuntu, ghc: 9.0.1 }
          - { os: macos, ghc: 9.0.1 }
          - { os: windows, ghc: 9.0.1 }
          - { os: ubuntu, ghc: 8.10.4 }
          - { os: ubuntu, ghc: 8.8.4 }
          - { os: ubuntu, ghc: 8.6.5 }
          - { os: ubuntu, ghc: 8.4.4 }
          - { os: ubuntu, ghc: 8.2.2 }
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal configure --enable-tests --flags pedantic --jobs
      - run: cabal freeze && cat cabal.project.freeze
      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ matrix.os }}-${{ matrix.ghc }}-
      - run: cabal test --test-show-details direct
      - run: cabal sdist
      - uses: actions/upload-artifact@v2
        with:
          path: dist-newstyle/sdist/witch-*.tar.gz
          name: witch-${{ github.sha }}.tar.gz
      - run: cabal check
      - if: github.event_name == 'release' && matrix.os == 'ubuntu' && matrix.ghc == '9.0.1'
        run: cabal upload --publish --username '${{ secrets.HACKAGE_USERNAME }}' --password '${{ secrets.HACKAGE_PASSWORD }}' dist-newstyle/sdist/witch-*.tar.gz
  i386:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - run: docker run --rm --user 0 --volume "$PWD:$PWD" --workdir "$PWD" taylorfausak/i386-haskell@sha256:450720742fa69258c0a8589dcac28c3c6d5d34718172d935b385520f4ee9128e sh -c 'cabal update && cabal test --test-show-details direct'
